---
flighdeck_motd_name: Solr 6.6

flightdeck_groups:
  - name: "solr"

flightdeck_users:
  - name: "solr"
    group: "solr"
    home: "/home/solr"

flightdeck_root_prompt: '\u@flightdeck-solr-8:\w# '
flightdeck_user_prompt: '\u@flightdeck-solr-8:\w$ '

flightdeck_motd_links:
  - name: 'Code & docs'
    url: 'https://github.com/ten7/flightdeck-solr-8'
  - name: ' Learn more'
    url: 'https://flightdeck.ten7.com/'

flightdeck_run_commands: |
  if [ -n "${FLIGHTDECK_CONFIG}" ]; then
    config_file=$(mktemp "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
    echo "$FLIGHTDECK_CONFIG" | base64 -d > $config_file
    ansible-playbook -i /ansible/inventories/all.ini -e "@${config_file}" /ansible/run.yml
  elif [ -f "${FLIGHTDECK_CONFIG_FILE}" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@${FLIGHTDECK_CONFIG_FILE}" /ansible/run.yml
  elif [ -f "/config/solr/flightdeck-solr.yml" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@/config/solr/flightdeck-solr.yml" /ansible/run.yml
  elif [ -f "/config/solr/flight-deck-solr.yml" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@/config/solr/flight-deck-solr.yml" /ansible/run.yml
  else
    ansible-playbook -i /ansible/inventories/all.ini /ansible/run.yml
  fi

flightdeck_path:
  - '/opt/solr/bin'

flightdeck_solr:
  port: "8983"
  cores: []
    # - name: "mysite_live"
    #   type: "search_api_solr"
    # - name: "othersite_live"
    #   type: "apachesolr"
    # - name: "blah"
    #   type: "custom"
    #   confDir: "/config/blah"
    #   dataDir: "/data/blah"
