---
- hosts: solr
  tasks:
    - name: Get list of existing cores
      uri:
        url: "http://127.0.0.1:{{ flightdeck_solr.port | default(flightdeck_solr_defaults.port) }}/solr/admin/cores"
        return_content: yes
        status_code:
          - 200
      register: _current_cores
      until: _current_cores.status == 200
      retries: 6
      delay: 15

    - name: Generate a flat list of core names
      set_fact:
        _wanted_cores: "{{ flightdeck_solr.cores | default([]) | map(attribute='name') | list }}"

    - name: Create cores
      command: >
        /opt/solr/bin/solr create -c {{ item }}
      when: item not in _current_cores.content
      loop: "{{ _wanted_cores }}"
